<div class="container">
    <div class="row">
        <div class="col-xs-12 col-md-6 col-md-offset-3">
            <h1>Cadastrar post</h1>
            <hr>
            <form name="form" method="post" action="/admin/posts/create">
                <div class="form-group">
                    <label for="title">
                        Título
                    </label>
                    <input class="form-control" id="title" type="text" name="title" />
                </div>
                <div class="form-group">
                    <label for="content">
                        Conteúdo
                    </label>
                    <textarea class="form-control" id="content" name="content"></textarea>
                </div>
                <button type="submit" class="btn btn-primary">
                    Enviar
                </button>
                <a href="<?php echo "/admin/posts/"; ?>" class="btn btn-default">
                    Voltar
                </a>
            </form>
        </div>
    </div>
</div>