<div class="container">
    <div class="row">
        <div class="col-xs-12 col-md-6 col-md-offset-2">
            <h1>Editar post</h1>
            <hr>
            <form name="form" method="post" action="<?php echo "/admin/posts/edit/{$post['id']}"; ?>">
                <div class="form-group">
                    <label for="title">
                        Título
                    </label>
                    <input class="form-control" id="title" type="text" name="title"
                            value="<?php echo $post['title'];?>"/>
                </div>
                <div class="form-group">
                    <label for="content">
                        Conteúdo
                    </label>
                    <textarea class="form-control" id="content" name="content"><?php echo $post['content'];?></textarea>
                </div>
                <button type="submit" class="btn btn-primary">
                    Salvar
                </button>
                <a href="<?php echo "/admin/posts/"; ?>" class="btn btn-default">
                    Voltar
                </a>
            </form>
        </div>
    </div>
</div>