version: '2'
services:
  silexbasico:
    container_name: silexbasico
    build: .
    restart: always
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/php/silexbasico
  # MySQL (5.7)
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    container_name: silexbasico-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=son_silex_basico
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root