<div class="container">
    <div class="row">
        <div class="col-xs-12 col-md-6 col-md-offset-3">
            <h1>Enviar Mensagem</h1>
            <hr>
            <form method="post" action="/fale-conosco">
                <div class="form-group">
                    <label for="nome">Nome</label>
                    <input type="text" class="form-control" name="nome" placeholder="Nome">
                </div>
                <div class="form-group">
                    <label for="email">E-mail</label>
                    <input type="email" class="form-control" name="email" placeholder="E-mail">
                </div>
                <div class="form-group">
                    <label for="mensagem">Mensagem</label>
                    <textarea class="form-control" name="mensagem" rows="3"></textarea>
                </div>
                <button type="submit" class="btn btn-primary pull-right">Enviar</button>
            </form>
        </div>
    </div>
</div>