<div class="page-header">
    <h1 class="text-center">App silex simples <small>nada demais por aqui</small></h1>
</div>

<div class="container">
    <div class="row">
        <div class="col-sm-12 col-md-4">
            <div class="thumbnail">
                <img src="https://wallpapers.wallhaven.cc/wallpapers/full/wallhaven-575741.jpg" alt="...">
                <div class="caption">
                    <h3>Thumbnail label</h3>
                    <p>...</p>
                    <p>
                        <a href="/admin/posts/" class="btn btn-info" role="button">Posts</a>
                        <a href="/listar-msg" class="btn btn-success" role="button">Mensagens</a></p>
                </div>
            </div>
        </div>
        <div class="col-sm-12 col-md-4">
            <div class="thumbnail">
                <img src="https://wallpapers.wallhaven.cc/wallpapers/full/wallhaven-575741.jpg" alt="...">
                <div class="caption">
                    <h3>Thumbnail label</h3>
                    <p>...</p>
                    <p>
                        <a href="/admin/posts/" class="btn btn-info" role="button">Posts</a>
                        <a href="/listar-msg" class="btn btn-success" role="button">Mensagens</a></p>
                </div>
            </div>
        </div>
        <div class="col-sm-12 col-md-4">
            <div class="thumbnail">
                <img src="https://wallpapers.wallhaven.cc/wallpapers/full/wallhaven-575741.jpg" alt="...">
                <div class="caption">
                    <h3>Thumbnail label</h3>
                    <p>...</p>
                    <p>
                        <a href="/admin/posts/" class="btn btn-info" role="button">Posts</a>
                        <a href="/listar-msg" class="btn btn-success" role="button">Mensagens</a></p>
                </div>
            </div>
        </div>
    </div>
</div>
